# facebook-App Settings: for SSO OAuth2 Target App
#server:
#  port: 8085
#security:
#  oauth2:
#    client:
#      clientId: 212036980162528
#      clientSecret: 34202f9cd5c2ab471a43675bbe252136
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

#
#
# Github-App Settings: for SSO OAuth2 Target App
server:
  port: 8085
security:
  oauth2:
    client:
      clientId: 231d6a75ee5f58b8295d
      clientSecret: 0f2df17c39cb2ed0e25a29a735d0fc72199073e7
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user